[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs
    | \.git
    | \.mypy_cache
    | \.venv
    | \.env
    | \.pytest_cache
    | _build
    | config
    | docs
    | build
    | dist
  )
)
'''
